---
# configure bind
- name: copy config files
  copy:
    src: named.conf
    dest: /etc/named.conf

- name: copy forward file
  template:
    src: forward.j2
    dest: /var/named/forward
- name:
  template:
    src: reverse.j2
    dest: /var/named/rev        
